### PR TITLE
Compile scss to css before publish to npm

### PR DESCRIPTION
**Pull request by ingro**
Following your comment at #1 I put up this PR. Basically I'm compiling from raw scss to css using `node-sass` using the `prepublish` npm's hook and then I use the compiled css in index.js instead of scss.

### CODE REVIEW

**Review by LouisBarranqueiro — CHANGES_REQUESTED** [review]
- Could you : 
- use `lib` instead of `dist`
- add a `.npmignore` file to exclude all files/folder for dev and now `src` folder

please :)

**Comment by ingro** [comment]
Sure, I'll do it asap!

**Comment by ingro** [comment]
@LouisBarranqueiro updated!

**Review by LouisBarranqueiro — APPROVED** [review]
LGTM. Thanks man :)

**Comment by ingro** [comment]
No problem, if you need I could send a PR also for bootstrap theme!

**Comment by LouisBarranqueiro** [comment]
Sure! :)

**Comment by ingro** [comment]
Created a PR for bootstrap theme too! I hope you can publish these soon! :)

**Comment by LouisBarranqueiro** [comment]
Just published :)

**Comment by ingro** [comment]
Thanks man!

**Pull request merged**
