### PR TITLE
Add Support for Create React App

### PR DESCRIPTION
**Pull request by zackify**
By renaming the css file to .module.css, this will work inside CRA without any ejecting or changes needed.

---
This change is [Reviewable](https://reviewable.io/reviews/louisbarranqueiro/reapop-theme-wybo/12)

### CODE REVIEW

**Review by LouisBarranqueiro — CHANGES_REQUESTED** [review]
> Reviewed 3 of 3 files at r1.
> *[Reviewable](https://reviewable.io/reviews/louisbarranqueiro/reapop-theme-wybo/12)* status: all files reviewed, 1 unresolved discussion (waiting on @zackify)

___
*[index.js, line 3 at r1](https://reviewable.io/reviews/louisbarranqueiro/reapop-theme-wybo/12#-LptvADC-TH5fn6MSXUy:-LptvADC-TH5fn6MSXUz:b4wv3gg) ([raw file](https://github.com/louisbarranqueiro/reapop-theme-wybo/blob/f985bffdc709b5c04f9a93d1c61c86291fb31c99/index.js#L3)):*
> ```JavaScript
> 'use strict';
> 
> var css = require('./lib/styles.module.css');
> ```

Please add this comment before the import explaining why it's important to keep this naming convention and prevent from changing it mistakenly in the future.
``` js
// In order for this theme to work straight out of the box with the Create React App project, we follow the same CSS Modules `[name].module.css` file naming convention.
```

**Comment by LouisBarranqueiro** [comment]
👋 @zackify I'm not a big fan of doing this because it creates some sort of link between these 2 unrelated projects, and this is not something scalable if the theme needs to work straight out of the box with different projects like Create React App. However, since there is only one for now, why not.

**Comment by henryruhs** [comment]
@LouisBarranqueiro Please merge this PR... people using Create React App are waiting for this.

I think there is a conflict `lib` vs. `styles` folder...

Thanks

**Comment by LouisBarranqueiro** [comment]
👋 @redaxmedia, I was waiting for the author to update the code based on the review. I will take care of it. 

> I think there is a conflict lib vs. styles folder...

what do you mean?

**Comment by henryruhs** [comment]
Sure but this are just 2 little edits... I had to copy the theme to make it work. Looking forward to it as I don't like to eject my config.

**Comment by LouisBarranqueiro** [comment]
I just released a new version: [reapop-theme-wybo@1.1.0](https://www.npmjs.com/package/reapop-theme-wybo). 🙂  Please let me know if it works as expected.

> Sure but this are just 2 little edits... I had to copy the theme to make it work.

@redaxmedia  I understand but I didn't rush the author to do the changes because this is an open-source project. I'm respectful of his time and contribution because we all have some other things to do. I appreciate that you reminded me that this PR was not merged but please do not forget that it's not because this project is open-source that I'm working for you, and that I have to be very responsive to your needs. I'm trying to share and help the community. Open source means: "if you want something, you can do it by yourself"; just like you did by doing the modifications yourself. 🙂

**Comment by henryruhs** [comment]
Don't worry, I do a lot OS myself and never considered you as someone to work for me.

Anyway, thanks a lot for the release.

**Pull request merged**
